### ISSUE TITLE
mrm overwrites package.json completely

### ISSUE THREAD

**Issue by maxgalbu** [adonisjs/mrm-preset#24]
running the following commands:

```bash
mkdir adonis-mrm-test
cd adonis-mrm-test
npm i -D mrm @adonisjs/mrm-preset
./node_modules/.bin/mrm  --preset=@adonisjs/mrm-preset package
```

results in package.json reduced to a file with this content:
```
license
```

If run after `mrm init`, it adds this:

```
{
 "0": "l",
  "1": "i",
  "2": "c",
  "3": "e",
  "4": "n",
  "5": "s",
  "6": "e",
}
```

**Comment by thetutlage** [comment]
I see why its happening without the `config.json` file in the place. I personally always run `npm run mrm init` first and then run any other scripts. So never faced this issue

**Comment by thetutlage** [comment]
Should be good with `^5.0.1`
